# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UploadImageToFirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UploadImageToFirebase
pod ‘Firebase’
pod ‘Firebase/Storage’
pod ‘Firebase/Core’
pod ‘Firebase/Auth’
pod 'Firebase/Database'
end
